# Generated by Django 5.0.3 on 2025-12-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autosave',
            old_name='deck',
            new_name='gameState',
        ),
        migrations.RemoveField(
            model_name='autosave',
            name='currentCard',
        ),
        migrations.RemoveField(
            model_name='autosave',
            name='playDirection',
        ),
        migrations.RemoveField(
            model_name='autosave',
            name='playerCards',
        ),
    ]
